name: Build

on:
  push:
    branches:
      - '1.20*'
      - 'feature/*'
  pull_request:
    branches:
      - '1.20*'
      - 'feature/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'
      - name: Setup Gradle
        run: ./gradlew
      - name: Build
        run: ./gradlew build
